### ISSUE TITLE
Generate circuit into a file

### ISSUE THREAD

**Issue by manel1874** [sine-fdn/garble-lang#107]
First of all, thank you for this amazing work!

Is there a simple command I can run to generate a circuit directly to a file? I am missing a cli tool for that. 

Or is there any other way to do it?

Thank you

**Comment by fkettelhoit** [comment]
Thank you for your interest in Garble!

Right now there is no way to write a circuit to a file, as we haven't decided on a serialization format. We use it directly in our MPC engine and so don't really load circuits from files. Currently the best way to do something like this would be to write your own serialization logic using the `Circuit` struct.
