### ISSUE TITLE
Replace public tuple structs by structs with named fields

### ISSUE THREAD

**Issue by raimundo-henriques** [sine-fdn/garble-lang#51]
### Context
There are several places in the code where we can find public tuple structs.

E.g. at lib/ast.rs:
```
pub struct ParamDef(pub Mutability, pub String, pub Type);
```

### Problem
As the fields of tuple structs are identified by index rather than .name (which they lack), this creates further difficulties when reading the code. This is more relevant concerning public parts of the code.

### Solution
Go through the code and replace all tuple structs by structs with appropriately named fields.

**Comment by fkettelhoit** [comment]
Fixed by #57
